apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tool-service-debug
spec:
  destination:
    name: ''
    namespace: fancytube-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: app/dev/tool-service-debug
    repoURL: 'https://github.com/bracebrace008/k8s-cd'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
