apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-debug
  namespace: elasticsearch
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
      nodePort: 30920
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elastic-instance
