apiVersion: v1
kind: Service
metadata:
  name: kafka-debug
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: tcp-clients
      port: 9092
      protocol: TCP
      targetPort: 9092
      nodePort: 30092
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
