apiVersion: v1
kind: Service
metadata:
  name: mysql-debug
  namespace: mysql-innerdbcluster
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
     targetPort: 32000
  selector:
    component: mysqlrouter
    mysql.oracle.com/cluster: mysql-innerdbcluster
    tier: mysql
