apiVersion: v1
kind: Service
metadata:
  name: nacos-debug
  namespace: nacos
spec:
  type: NodePort
  ports:
    - name: client
      port: 8848
      protocol: TCP
      targetPort: 8848
      nodePort: 30848
  selector:
    app: nacos
    app.kubernetes.io/instance: nacos
    component: nacos
    middleware: nacos
