{{- define "common-chart.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
    spec:
      tolerations:
        - key: pool-prod
          operator: Exists
          effect: NoSchedule
      containers:
        - name: "{{ .Values.appName }}"
          # image: $DOCKER_NAMESPACE/"{{ .Values.appName }}":$BUILD_TIME
          image: "bracebrace008/fancytube-h5-frontend:{{ .Values.tag }}"
          ports:
            - containerPort: 3000
{{- end -}}