{{- define "common-chart.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
    spec:
      tolerations:
        - key: pool-prod
          operator: Exists
          effect: NoSchedule
      containers:
        - name: "{{ .Values.appName }}"
          image: "bracebrace008/{{ .Values.appName }}:{{ .Values.tag }}"
          ports:
            - containerPort: {{ .Values.appPort }}
{{- end -}}