{{- define "common-chart.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
    spec:
      containers:
        - name: "{{ .Values.appName }}"
          image: "bracebrace008/{{ .Values.appName }}:{{ .Values.tag }}"
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-token-secret
                key: token      
          ports:
            - containerPort: {{ .Values.appPort }}
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}" 
{{- end -}}