{{- define "common-chart.service" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}    
  selector:
    app: {{ .Values.appName }}
{{- end -}}    
