apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000      
  selector:
    app: {{ .Values.appName }}
