apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: kafka-cluster
    repoURL: 'https://github.com/bracebrace008/k8s-cd'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
