apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-instance
spec:
  version: {{ .Chart.AppVersion }}
  nodeSets:
  - name: default
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: openebs-hostpath
    config:
      node.store.allow_mmap: false  
    podTemplate:
      spec:
         initContainers:
         - name: install-plugins
           command: 
           - sh
           - -c
           - |
             bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v{{ .Chart.AppVersion }}/elasticsearch-analysis-ik-{{ .Chart.AppVersion }}.zip
  http:
    tls:
      selfSignedCertificate:
        disabled: true        