kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
  namespace: fancytube-dev
  annotations:
    kubesphere.io/creator: admin
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - fancytube-test.xyz
    - fancytube.io
    secretName: {{ .Values.appName }}-tls
  rules:
    - host: fancytube-test.xyz
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName }}-svc
                port:
                  number: 3000
    - host: fancytube.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName }}-svc
                port:
                  number: 3000              
