apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    path: cert-manager
    repoURL: "https://github.com/bracebrace008/k8s-cd"
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
